layout_spectrum: 0.2346072
typography_spectrum: 0.8335088
color:
  lightness: 0.134673
  brandStrength: 0.103499
  saturation: 0.6904199
  rhythmicContrast: 0.381153
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Different Gifts
